"""add_custom_fee_to_projects

Revision ID: 38dc26e8c758
Revises: 37de355484a0
Create Date: 2026-04-12 10:45:54.618575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dc26e8c758'
down_revision: Union[str, Sequence[str], None] = '37de355484a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('custom_fee', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'custom_fee')
    # ### end Alembic commands ###
